### ISSUE TITLE
Upgrade to Spring Framework 5.0

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/jpetstore-6#133]
@mybatis/committers
I want to upgrade to Spring Framework 5.0.

Which is better?

* Update major version up on this project. (e.g. 7.0.0)
* Create new repository(artifact)? (e.g. jpetstpre-7???)
* other ...

What mean `6` of `jpetstore-6`?

**Comment by harawata** [comment]
Thank you @kazuki43zoo for keeping jpetstore up to date!

Simply upgrading to Spring 5 should be fine if that is possible.
We may bump the version number when the site gets major design update or the app is rewritten with the next major version of MyBatis.

> What mean 6 of jpetstore-6?

The current jpetstore is version 6.
Version 1 was released in 2002 🦕 according to [Wikipedia](https://en.wikipedia.org/wiki/IBATIS#History).

**Comment by hazendaz** [comment]
bumping spring to 5 will require bumping this to java 8 usage.  That does sound like version 7.0.0 but also seems we need to drop the -6 off the name which I think we can simply rename on github.
