### ISSUE TITLE
Can't Deploy Package

### ISSUE THREAD

**Issue by kaneishere** [mybatis/jpetstore-6#221]
I'm using maven in intellij idea to deploy the package. I got this error

Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy (default-deploy) on project jpetstore: ArtifactDeployerException: Failed to deploy artifacts: Could not transfer artifact org.mybatis:jpetstore:war:6.0.3-20190715.160857-79 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/jpetstore/6.0.3-SNAPSHOT/jpetstore-6.0.3-20190715.160857-79.war. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

Please advise

**Comment by hazendaz** [comment]
@kaneishere Deploy is used to push to a nexus repo.  That is not what you would be doing.  You are appropriately blocked from 'deployment' as you would have to be a member of the mybatis team.  Presumably you would be running ```mvn clean install``` to produce a war file which is one phase before deploy.  You might further use one of the cargo maven plugin setups in the build to run on a given container locally or you might simply take the WAR and put into your applicatinon container directly.

I'm closing this ticket as this is not related to this library but rather use of maven plugin usage.
