### ISSUE TITLE
JPetShop with Azure Application Insight

### ISSUE THREAD

**Issue by dipietro-salvatore** [mybatis/jpetstore-6#73]
Hi everyone,
I would like to to test the Application Insight tool of Microsoft Azure. For this reason, I took a Java EE application (jpetshop) and I am trying to set up the Application Insight on top of it following this guide: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started

I added the Maven dependency and repository and, thanks to Eclipse, I created the ApplicationInsights.xml file with my InstrumentationKey. The only thing that I am not sure about is how to add is the HTTP filter on this application (point 4).

I added this to the filter block:
    <filter>
.....
     </init-param>
     <init-param>
            <param-name>ApplicationInsightsRequestNameInterceptor</param-name>
            <param-value>com.microsoft.applicationinsights.web.struts.RequestNameInterceptor</param-value>
        </init-param>     
    </filter>

But I don't know how to add the filter <filter-mapping> and make it works with Spring and Stripes.
Do you know how can I do that? 

Thank you

**Comment by jeffgbutler** [comment]
Please ask questions on the user mailing list.

jpetstore doesn't use Struts or SpringMVC, so you can only add the general http filter shown at the beginning of step 4.
